### PR TITLE
Updated Sample GDS Docker (Compose) Deployment

### PR DESCRIPTION
**Pull request by maxschiffer**
## Proposed changes

Updated and streamlined the Docker deployment for the sample GDS.
Changes made:
- Updated the base image from net6.0-bullseye-slim to net6.0-bookworm-slim
- Integrated the build process in docker, so no dotnet is required on the host
    - therefore the dotnet image is now the dotnet sdk and no longer the dotnet runtime
- added a docker compose file, for easy "1-click" test deployments 
    - added volume mounts to allow easier management of the config files and certificates
- added a readme.md file that explains the different deployment options
- removed the dockerrun.bat script, because it's no longer required, since the readme.md now explains the different available deployment options.

## Related Issues

- none really, just improvements

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR._

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] Enhancement (non-breaking change which adds functionality)
- [ ] Test enhancement (non-breaking change to increase test coverage)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected, requires version increase of Nuget packages)
- [x] Documentation Update (if none of the other choices apply)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._

- [x] I have read the [CONTRIBUTING](https://github.com/OPCFoundation/UA-.NETStandard/blob/master/CONTRIBUTING.md) doc.
- [x] I have signed the [CLA](https://opcfoundation.org/license/cla/ContributorLicenseAgreementv1.0.pdf).
- [x] I ran tests locally with my changes, all passed.
- [x] I fixed all failing tests in the CI pipelines. 
- [x] I fixed all introduced issues with CodeQL and LGTM.
- [x] I have added tests that prove my fix is effective or that my feature works and increased code coverage.
- [x] I have added necessary documentation (if appropriate).
- [x] Any dependent changes have been merged and published in downstream modules.

## Further comments

Since no actual code was changed, I just checked all the test checkboxes above. I've tested all the deployment options and connected to the GDS using the GlobalDiscoveryClient from this repository. This is

### CODE REVIEW

**Review by mregen — COMMENTED** [review]
nice work!

**Comment by maxschiffer** [comment]
Thanks, so how do we proceed merging this onto the main branch?

The unsuccessful checks are apperarantly caused by something going wrong with the xamarin build on the main branch - which this PR does not touch at all.

**Comment by mregen** [comment]
Thanks, the Xamarin build needs to be fixed or deprecated. I can proceed and check with the latest stack update.

**Comment by maxschiffer** [comment]
Don't worry, I just fixed it: [](https://github.com/OPCFoundation/UA-.NETStandard-Samples/pull/574)
The UWP build error was easy to fix, the Xamarin Issue was a bit trickier since some old StackOverflow posts and microsoft forum posts were misleading by mentioning issues with the Android SDK 25. 
This was not the case - it was due to an update of the base image used when building: The lowest available SDK version on the win2022 image is the Android SDK27 (Android 8.1).

**Review by mregen — APPROVED** [review]

**Comment by mregen** [comment]
nice work! all building!

**Pull request merged**
